### PR TITLE
integration test for "Reactor project wants to have License XML in Aggregator POM."

### PR DESCRIPTION
**Pull request by Tibor17**
The IT with Maven multi-module project for the configuration parameter `licenseFile`.

### CODE REVIEW

**Comment by Tibor17** [comment]
@smuda 
This is the IT.
As a notice, the users should see some documentation regarding these features. You want to do it or should I add a docu for `licenseFile` in the README.md and MOJO.

**Comment by smuda** [comment]
@Tibor17 
This looks really good. Please add yourself as a contributor in the readme.

If you have the time, please add documentation for the licenseFile, otherwise I'll do it a bit later.

**Review by smuda — APPROVED** [review]

**Comment by Tibor17** [comment]
@smuda done

**Comment by Tibor17** [comment]
I will rebase and force push in this PR.

**Comment by Tibor17** [comment]
@smuda 
ok, now the PR is rebased on the top HEAD of master and can be pushed to remote.

**Pull request merged**
